baseURL: "https://domin-alejandro.netlify.app/"
languageCode: "en-us"
title: "Domin"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true



params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Blog Informática
    description: "Esta es la descripción de mi pagina"
    keywords: [Blog, Portfolio, PaperMod]
    author: Alejandro Dominguez Alcocer
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://wallery.app/dufovot/colored-lion-wallpaper.webp"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Alejandro Domínguez"
        icon: "https://i.pinimg.com/originals/d6/00/86/d600863ad0cfbac83799ffd1492ab2fb.jpg"
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "http://herramientasgratis.com/wp-content/uploads/2020/01/29-291287_yellow-4k-ultra-hd-wallpaper-fondo-amarillo-hd-scaled.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "BLOG PERSONAL \U0001F427"
        Content: Bienvenido, este es mi blog personal donde subire todos los trabajos que realize este segundo curso del Gonzalo Nazareno.

    socialIcons:
        - name: twitter
          url: "https://twitter.com/"
        - name: stackoverflow
          url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/Domin01"
        - name: discord
          url: "https://discord.gg/XtnfrpNF"
        - name: paypal
          url : "https://paypal.com"
        - name: youtube
          url : "https://youtube.com"
        - name: steam
          url : "https://store.steampowered.com/?l=spanish"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/Domin01/hugo-estatica"
        Text: "Sugiere un cambio" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: windows
          name: Windows
          url: /windows/
          weight: 10
        - identifier: linux
          name: Linux
          url: /linux/
          weight: 20
        - identifier: example
          name: Web Gonzalo Nazareno
          url: https://dit.gonzalonazareno.org/gestiona/
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
#pygmentsUseClasses: true
#markup:
#    highlight:
#    anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
